# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# Define que qualquer commit na branch 'main' dispara a pipeline
trigger:
- main

resources:
- repo: self

pool:
  name: 'Default'
  
variables:
  dockerRegistryServiceConnection: 'ConexaoDockerHub' 
  imageRepository: 'feliperesendebr/unyleya_projeto_hub_docker' 
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  webAppNameDev: 'unyleya-app' # Nomes dos App Services (Crie um segundo se quiser isolar dev de prod)
  webAppNameProd: 'unyleya-app'
  
stages:
- stage: Build
  displayName: Build and Push Stage
  jobs:
  - job: BuildJob
    displayName: Build
    steps:
    # A Task Docker@2 gerencia login, build, tag e push automaticamente
    - task: Docker@2
      displayName: Build and Push to Docker Hub
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest

- stage: DeployDev
  displayName: Deploy Stage Development
  dependsOn: Build 
  condition: succeeded()  
  jobs:
  - deployment: DeployDevJob
    environment: 'Development'
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureWebAppContainer@1
              inputs:
                azureSubscription: 'ConexaoAzure'
                appName: '$(webAppNameDev)'
                imageName: '$(imageRepository):$(tag)'

- stage: DeployProd
  displayName: Deploy Stage Production
  dependsOn: DeployDev
  condition: succeeded()  
  jobs:
  - deployment: DeployProdJob
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self 
              persistCredentials: true          
            - task: AzureWebAppContainer@1
              inputs:
                azureSubscription: 'ConexaoAzure'
                appName: '$(webAppNameProd)'
                imageName: '$(imageRepository):$(tag)'                